[package]
name = "censor"
version = "0.2.0"
authors = ["Quickmarble"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
json = "0.12.4"
clap = "2.33.3"
ureq = "2.1.1"
